### ISSUE TITLE
复现请教

### ISSUE THREAD

**Issue by Andy-HuY** [GeoX-Lab/LSTTN#2]
@GeoX-Lab 作者您好，首先非常感谢开源。运行main.py出现以下问题，暂时无法解决，easytorch版本是一致的。
root@autodl-container-9dfa4d997e-0f7507ef:~/autodl-tmp/LSTTN-main# python main.py
2024-04-16 12:49:16,861 - easytorch-launcher - INFO - Launching EasyTorch training.
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    launch_training(args)
  File "/root/miniconda3/lib/python3.8/site-packages/easytorch/launcher/launcher.py", line 59, in launch_training
    cfg = init_cfg(cfg, node_rank == 0)
  File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/utils.py", line 215, in init_cfg
    cfg = convert_config(cfg)
  File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/utils.py", line 188, in convert_config
    cfg = Config(cfg)
  File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/config.py", line 135, in __init__
    for k, v in dict.items():
AttributeError: 'Namespace' object has no attribute 'items'

**Comment by 1073535050** [comment]
同学你好，我在复现时也遇到easytorch问题，请问方便加个联系方式一起探讨一下吗？

**Comment by Andy-HuY** [comment]
好的，你邮箱多少，我联系你



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月16日(周二) 下午3:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [GeoX-Lab/LSTTN] 复现请教 (Issue #2)




 
同学你好，我在复现时也遇到easytorch问题，请问方便加个联系方式一起探讨一下吗？

**Comment by 1073535050** [comment]
1073535050@qq.com

**Comment by GeoX-Lab** [comment]
不好意思，easytorch在requirements里面是错误的，实际上是另一个easytorch包。直接用`pip install easy-torch`安装即可。

**Comment by Andy-HuY** [comment]
> 不好意思，easytorch在requirements里面是错误的，实际上是另一个easytorch包。直接用`pip install easy-torch`安装即可。

好的，谢谢您的回复。再请教下，目前碰到一个错误，请帮忙看看是哪里没有搞对呢？
root@autodl-container-59c811a43c-e7c3df04:~/autodl-tmp/LSTTN-main# python main.py
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from configs.PEMS04.forecasting import CFG
  File "/root/autodl-tmp/LSTTN-main/configs/PEMS04/forecasting.py", line 12, in <module>
    adj_mx, _ = load_adj(GRAPH_PKL_PATH, "doubletransition")
  File "/root/autodl-tmp/LSTTN-main/utils/log.py", line 10, in clocked
    result = func(*args, **kw)
  File "/root/autodl-tmp/LSTTN-main/utils/load_data.py", line 70, in load_adj
    adj = [transition_matrix(adj_mx).T, transition_matrix(adj_mx.T).T]
  File "/root/autodl-tmp/LSTTN-main/utils/adj_mx.py", line 41, in transition_matrix
    adj = sp.coo_matrix(adj)
  File "/root/miniconda3/lib/python3.8/site-packages/scipy/sparse/coo.py", line 181, in __init__
    raise TypeError('expected dimension <= 2 array or matrix')
TypeError: expected dimension <= 2 array or matrix

导入到 adj = sp.coo_matrix(adj)的adj是（16992， 307，3）这样形状，是之前哪一步载入出错了吗？

forecasting.py 里面第10行是这样载入的
GRAPH_PKL_PATH = "datasets/sensor_graph/adj_mx_04.pkl"
NUM_NODES = 307

**Comment by cxt1314520** [comment]
> 不好意思，easytorch在requirements里面是错误的，实际上是另一个easytorch包。直接用`pip install easy-torch`安装即可。



> 不好意思，easytorch在requirements里面是错误的，实际上是另一个easytorch包。直接用`pip install easy-torch`安装即可。

你好，我用的是pip install easy-torch，但还是去出现以下问题：AttributeError: 'Namespace' object has no attribute 'items'

**Comment by cxt1314520** [comment]
> @GeoX-Lab 作者您好，首先非常感谢开源。运行main.py出现以下问题，暂时无法解决，easytorch版本是一致的。 root@autodl-container-9dfa4d997e-0f7507ef:~/autodl-tmp/LSTTN-main# python main.py 2024-04-16 12:49:16,861 - easytorch-launcher - INFO - Launching EasyTorch training. Traceback (most recent call last): File "main.py", line 14, in launch_training(args) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/launcher/launcher.py", line 59, in launch_training cfg = init_cfg(cfg, node_rank == 0) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/utils.py", line 215, in init_cfg cfg = convert_config(cfg) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/utils.py", line 188, in convert_config cfg = Config(cfg) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/config.py", line 135, in **init** for k, v in dict.items(): AttributeError: 'Namespace' object has no attribute 'items'

楼主你好，我第一次复现文章，用的是pip install easy-torch，但还是出现以下问题（感觉和你非常相似）：AttributeError: 'Namespace' object has no attribute 'items'
不知道楼主能否帮忙解答，万分感谢

**Comment by Andy-HuY** [comment]
> > @GeoX-Lab 作者您好，首先非常感谢开源。运行main.py出现以下问题，暂时无法解决，easytorch版本是一致的。 root@autodl-container-9dfa4d997e-0f7507ef:~/autodl-tmp/LSTTN-main# python main.py 2024-04-16 12:49:16,861 - easytorch-launcher - INFO - Launching EasyTorch training. Traceback (most recent call last): File "main.py", line 14, in launch_training(args) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/launcher/launcher.py", line 59, in launch_training cfg = init_cfg(cfg, node_rank == 0) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/utils.py", line 215, in init_cfg cfg = convert_config(cfg) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/utils.py", line 188, in convert_config cfg = Config(cfg) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/config.py", line 135, in **init** for k, v in dict.items(): AttributeError: 'Namespace' object has no attribute 'items'
> 
> 楼主你好，我第一次复现文章，用的是pip install easy-torch，但还是出现以下问题（感觉和你非常相似）：AttributeError: 'Namespace' object has no attribute 'items' 不知道楼主能否帮忙解答，万分感谢

这个在作者那个question提示里面，main.py里面加两行就行了
from configs.PEMS04.forecasting import CFG

launch_training(CFG)

**Comment by cxt1314520** [comment]
> > > @GeoX-Lab 作者您好，首先非常感谢开源。运行main.py出现以下问题，暂时无法解决，easytorch版本是一致的。 root@autodl-container-9dfa4d997e-0f7507ef:~/autodl-tmp/LSTTN-main# python main.py 2024-04-16 12:49:16,861 - easytorch-launcher - INFO - Launching EasyTorch training. Traceback (most recent call last): File "main.py", line 14, in launch_training(args) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/launcher/launcher.py", line 59, in launch_training cfg = init_cfg(cfg, node_rank == 0) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/utils.py", line 215, in init_cfg cfg = convert_config(cfg) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/utils.py", line 188, in convert_config cfg = Config(cfg) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/config.py", line 135, in **init** for k, v in dict.items(): AttributeError: 'Namespace' object has no attribute 'items'
> > 
> > 
> > 楼主你好，我第一次复现文章，用的是pip install easy-torch，但还是出现以下问题（感觉和你非常相似）：AttributeError: 'Namespace' object has no attribute 'items' 不知道楼主能否帮忙解答，万分感谢
> 
> 这个在作者那个question提示里面，main.py里面加两行就行了 from configs.PEMS04.forecasting import CFG
> 
> launch_training(CFG)

楼主，你好，感谢回复，这个我也加了 ，直接在main里面加的
import argparse
from easytorch import launch_training
from configs.PEMS04.forecasting import CFG
launch_training(CFG)
但还是出现上述问题，现在用conda从新创个环境，不知道楼主是否复现，可以加个好友指导一下吗，万分感谢

**Comment by Andy-HuY** [comment]
> > > > @GeoX-Lab 作者您好，首先非常感谢开源。运行main.py出现以下问题，暂时无法解决，easytorch版本是一致的。 root@autodl-container-9dfa4d997e-0f7507ef:~/autodl-tmp/LSTTN-main# python main.py 2024-04-16 12:49:16,861 - easytorch-launcher - INFO - Launching EasyTorch training. Traceback (most recent call last): File "main.py", line 14, in launch_training(args) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/launcher/launcher.py", line 59, in launch_training cfg = init_cfg(cfg, node_rank == 0) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/utils.py", line 215, in init_cfg cfg = convert_config(cfg) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/utils.py", line 188, in convert_config cfg = Config(cfg) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/config.py", line 135, in **init** for k, v in dict.items(): AttributeError: 'Namespace' object has no attribute 'items'
> > > 
> > > 
> > > 楼主你好，我第一次复现文章，用的是pip install easy-torch，但还是出现以下问题（感觉和你非常相似）：AttributeError: 'Namespace' object has no attribute 'items' 不知道楼主能否帮忙解答，万分感谢
> > 
> > 
> > 这个在作者那个question提示里面，main.py里面加两行就行了 from configs.PEMS04.forecasting import CFG
> > launch_training(CFG)
> 
> 楼主，你好，感谢回复，这个我也加了 ，直接在main里面加的 import argparse from easytorch import launch_training from configs.PEMS04.forecasting import CFG launch_training(CFG) 但还是出现上述问题，现在用conda从新创个环境，不知道楼主是否复现，可以加个好友指导一下吗，万分感谢

我也是这样的哎，但是没报错，我之前试过把这两行删掉就会报你那个错误。我还没复现，怕是谈不上指导，目前卡在一个GPU的问题了。要不请你给我个邮箱，我们共同探讨下吧

**Comment by cxt1314520** [comment]
> > > > > @GeoX-Lab 作者您好，首先非常感谢开源。运行main.py出现以下问题，暂时无法解决，easytorch版本是一致的。 root@autodl-container-9dfa4d997e-0f7507ef:~/autodl-tmp/LSTTN-main# python main.py 2024-04-16 12:49:16,861 - easytorch-launcher - INFO - Launching EasyTorch training. Traceback (most recent call last): File "main.py", line 14, in launch_training(args) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/launcher/launcher.py", line 59, in launch_training cfg = init_cfg(cfg, node_rank == 0) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/utils.py", line 215, in init_cfg cfg = convert_config(cfg) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/utils.py", line 188, in convert_config cfg = Config(cfg) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/config.py", line 135, in **init** for k, v in dict.items(): AttributeError: 'Namespace' object has no attribute 'items'
> > > > 
> > > > 
> > > > 楼主你好，我第一次复现文章，用的是pip install easy-torch，但还是出现以下问题（感觉和你非常相似）：AttributeError: 'Namespace' object has no attribute 'items' 不知道楼主能否帮忙解答，万分感谢
> > > 
> > > 
> > > 这个在作者那个question提示里面，main.py里面加两行就行了 from configs.PEMS04.forecasting import CFG
> > > launch_training(CFG)
> > 
> > 
> > 楼主，你好，感谢回复，这个我也加了 ，直接在main里面加的 import argparse from easytorch import launch_training from configs.PEMS04.forecasting import CFG launch_training(CFG) 但还是出现上述问题，现在用conda从新创个环境，不知道楼主是否复现，可以加个好友指导一下吗，万分感谢
> 
> 我也是这样的哎，但是没报错，我之前试过把这两行删掉就会报你那个错误。我还没复现，怕是谈不上指导，目前卡在一个GPU的问题了。要不请你给我个邮箱，我们共同探讨下吧

万分感谢，小白一枚：1050504860@qq.com

**Comment by yunxin108** [comment]
你好 版主,
我在复現時遇到以下問題:
FileNotFoundError: [Errno 2] No such file or directory: '../datasets/sensor_graph/adj_mx_04.pkl'
想請問pkl檔案要在哪邊下載
謝謝

**Comment by Andy-HuY** [comment]
> 你好 版主, 我在复現時遇到以下問題: FileNotFoundError: [Errno 2] No such file or directory: '../datasets/sensor_graph/adj_mx_04.pkl' 想請問pkl檔案要在哪邊下載 謝謝

是不是下载数据集的时候一起有？
![1715183448852](https://github.com/GeoX-Lab/LSTTN/assets/22949761/248eb0f7-8698-44f7-a390-195ce7647462)

**Comment by cxt1314520** [comment]
> 你好 版主， 我在复現時遇到以下問題： FileNotFoundError： [Errno 2] No such file or directory： '../datasets/sensor_graph/adj_mx_04.pkl' 想請問pkl檔案要在哪邊下載 謝謝

同志，你好，根据作者githu上面的指导下载的，没有问题哦

**Comment by cxt1314520** [comment]
> > 你好 版主， 我在复現時遇到以下問題： FileNotFoundError： [Errno 2] No such file or directory： '../datasets/sensor_graph/adj_mx_04.pkl' 想請問PKL檔案要在哪邊下載 謝謝
> 
> 是不是下载数据集的时候一起有？ ![1715183448852](https://private-user-images.githubusercontent.com/22949761/328955308-248eb0f7-8698-44f7-a390-195ce7647462.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDU5OTgsIm5iZiI6MTcxNTI0NTY5OCwicGF0aCI6Ii8yMjk0OTc2MS8zMjg5NTUzMDgtMjQ4ZWIwZjctODY5OC00NGY3LWEzOTAtMTk1Y2U3NjQ3NDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA5MDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MDA1MzA4NTJlMmIwMzQ5OGM0Mjg4NWVmMWM3ZGZjOTUzMDhlYWM5ZTQyYTdhZmMxMGUzYTM1MGNkMWM0ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Q-DmsZwhtK5w1DYX7xbNa5ISTWJvnhj0VODCqFkTxw)

有的有的，但是并没有复现

**Comment by ry123scuer** [comment]
> > > 你好 版主， 我在复現時遇到以下問題： FileNotFoundError： [Errno 2] No such file or directory： '../datasets/sensor_graph/adj_mx_04.pkl' 想請問PKL檔案要在哪邊下載 謝謝
> > 
> > 
> > 是不是下载数据集的时候一起有？ ![1715183448852](https://private-user-images.githubusercontent.com/22949761/328955308-248eb0f7-8698-44f7-a390-195ce7647462.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDU5OTgsIm5iZiI6MTcxNTI0NTY5OCwicGF0aCI6Ii8yMjk0OTc2MS8zMjg5NTUzMDgtMjQ4ZWIwZjctODY5OC00NGY3LWEzOTAtMTk1Y2U3NjQ3NDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA5MDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MDA1MzA4NTJlMmIwMzQ5OGM0Mjg4NWVmMWM3ZGZjOTUzMDhlYWM5ZTQyYTdhZmMxMGUzYTM1MGNkMWM0ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Q-DmsZwhtK5w1DYX7xbNa5ISTWJvnhj0VODCqFkTxw)
> 
> 有的有的，但是并没有复现

同学你好，请问年解决将吗？我也遇到了这个问题，明明已经下载数据集了，也有这个路径，但是就是和你报一样的错

**Comment by ThisAngryman** [comment]
RuntimeError: Device num not match, cfg.DEVICE_NUM = 2, but torch.cuda.device_count() = 0
有人遇到这个问题吗？设备数量不匹配怎么要在哪里修改

**Comment by ThisAngryman** [comment]
RuntimeError: Device num not match, cfg.DEVICE_NUM = 2, but torch.cuda.device_count() = 0
有人遇到这个问题吗？我用的torch版本是1.8.1gpu的但还是报这个错误

**Comment by 1zhd** [comment]
> > > > > > @GeoX-Lab 作者您好，首先非常感谢开源。运行main.py出现以下问题，暂时无法解决，easytorch版本是一致的。 root@autodl-container-9dfa4d997e-0f7507ef:~/autodl-tmp/LSTTN-main# python main.py 2024-04-16 12:49:16,861 - easytorch-launcher - INFO - Launching EasyTorch training. Traceback (most recent call last): File "main.py", line 14, in launch_training(args) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/launcher/launcher.py", line 59, in launch_training cfg = init_cfg(cfg, node_rank == 0) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/utils.py", line 215, in init_cfg cfg = convert_config(cfg) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/utils.py", line 188, in convert_config cfg = Config(cfg) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/config.py", line 135, in **init** for k, v in dict.items(): AttributeError: 'Namespace' object has no attribute 'items'
> > > > > 
> > > > > 
> > > > > 楼主你好，我第一次复现文章，用的是pip install easy-torch，但还是出现以下问题（感觉和你非常相似）：AttributeError: 'Namespace' object has no attribute 'items' 不知道楼主能否帮忙解答，万分感谢
> > > > 
> > > > 
> > > > 这个在作者那个question提示里面，main.py里面加两行就行了 from configs.PEMS04.forecasting import CFG
> > > > launch_training(CFG)
> > > 
> > > 
> > > 楼主，你好，感谢回复，这个我也加了 ，直接在main里面加的 import argparse from easytorch import launch_training from configs.PEMS04.forecasting import CFG launch_training(CFG) 但还是出现上述问题，现在用conda从新创个环境，不知道楼主是否复现，可以加个好友指导一下吗，万分感谢
> > 
> > 
> > 我也是这样的哎，但是没报错，我之前试过把这两行删掉就会报你那个错误。我还没复现，怕是谈不上指导，目前卡在一个GPU的问题了。要不请你给我个邮箱，我们共同探讨下吧
> 
> 万分感谢，小白一枚：[1050504860@qq.com](mailto:1050504860@qq.com)

你好，我这边也出现了楼主一样的问题；from configs.PEMS04.forecasting import CFG和launch_training(CFG)也已经加到了main函数里面，但是还是有：AttributeError: 'Namespace' object has no attribute 'items'；请问楼主这个问题有解决嘛？

**Comment by Andy-HuY** [comment]
不好意思，我没有解决到就没继续了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月15日(周一) 下午5:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [GeoX-Lab/LSTTN] 复现请教 (Issue #2)




       
@GeoX-Lab 作者您好，首先非常感谢开源。运行main.py出现以下问题，暂时无法解决，easytorch版本是一致的。 ***@***.***:~/autodl-tmp/LSTTN-main# python main.py 2024-04-16 12:49:16,861 - easytorch-launcher - INFO - Launching EasyTorch training. Traceback (most recent call last): File "main.py", line 14, in launch_training(args) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/launcher/launcher.py", line 59, in launch_training cfg = init_cfg(cfg, node_rank == 0) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/utils.py", line 215, in init_cfg cfg = convert_config(cfg) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/utils.py", line 188, in convert_config cfg = Config(cfg) File "/root/miniconda3/lib/python3.8/site-packages/easytorch/config/config.py", line 135, in init for k, v in dict.items(): AttributeError: 'Namespace' object has no attribute 'items'
  
楼主你好，我第一次复现文章，用的是pip install easy-torch，但还是出现以下问题（感觉和你非常相似）：AttributeError: 'Namespace' object has no attribute 'items' 不知道楼主能否帮忙解答，万分感谢
  
这个在作者那个question提示里面，main.py里面加两行就行了 from configs.PEMS04.forecasting import CFG
 launch_training(CFG)
  
楼主，你好，感谢回复，这个我也加了 ，直接在main里面加的 import argparse from easytorch import launch_training from configs.PEMS04.forecasting import CFG launch_training(CFG) 但还是出现上述问题，现在用conda从新创个环境，不知道楼主是否复现，可以加个好友指导一下吗，万分感谢
  
我也是这样的哎，但是没报错，我之前试过把这两行删掉就会报你那个错误。我还没复现，怕是谈不上指导，目前卡在一个GPU的问题了。要不请你给我个邮箱，我们共同探讨下吧
  
***@***.***
  
你好，我这边也出现了楼主一样的问题；from configs.PEMS04.forecasting import CFG和launch_training(CFG)也已经加到了main函数里面，但是还是有：AttributeError: 'Namespace' object has no attribute 'items'；请问楼主这个问题有解决嘛？
