### ISSUE TITLE
数据集应该是什么目录结构呢

### ISSUE THREAD

**Issue by ry123scuer** [GeoX-Lab/LSTTN#6]
Traceback (most recent call last):
  File "/home/ren/公共的/ry/LSTTN-main/main.py", line 3, in <module>
    from configs.PEMS04.forecasting import CFG
  File "/home/ren/公共的/ry/LSTTN-main/configs/PEMS04/forecasting.py", line 12, in <module>
    adj_mx, _ = load_adj(GRAPH_PKL_PATH, "doubletransition")
  File "/home/ren/公共的/ry/LSTTN-main/utils/log.py", line 10, in clocked
    result = func(*args, **kw)
  File "/home/ren/公共的/ry/LSTTN-main/utils/load_data.py", line 60, in load_adj
    adj_mx = load_pkl('../datasets/sensor_graph/adj_mx_04.pkl')
  File "/home/ren/公共的/ry/LSTTN-main/utils/log.py", line 21, in load_pkl
    with open(pickle_file, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '../datasets/sensor_graph/adj_mx_04.pkl'
Unable to load data  ../datasets/sensor_graph/adj_mx_04.pkl : [Errno 2] No such file or directory: '../datasets/sensor_graph/adj_mx_04.pkl'
我下载了作者提供的数据集，但是报错了。以下是我的数据集目录，请大佬指点！
![Uploading QQ20240621-143049.png…]()

**Comment by ry123scuer** [comment]
![image](https://github.com/GeoX-Lab/LSTTN/assets/152693205/c617ada4-f7f2-4c76-9e31-9e79e051de2a)
